
- name: "Make sure config dicts exist"
  set_fact:
    django_cert: "{{ django_cert|default({}) }}"
    django_server: "{{ django_server|default({}) }}"
    django_web: "{{ django_web|default({}) }}"

# We cannot override django_server because facts and role parameters live in
# different namespaces, where role params take precedence. So we would have a
# django_server role param and a django_server fact, with the role param taking
# precedence.

- set_fact:
    django_cert_combined: "{{ django_cert_defaults | combine(django_cert, recursive=True) }}"
    django_server_combined: "{{ django_server_defaults | combine(django_server, recursive=True) }}"
    django_web_combined: "{{ django_web_defaults | combine(django_web, recursive=True) }}"

- debug: var=django_web_combined
