#
# Setup database
#
# Input : django_root, dir_venv
# Output:
# Requires: dir_venv, settings
#

# FIXME It says 'ok' when it should say 'changed'
- name: "Create database"
  django_manage:
    virtualenv: "{{ dir_venv|default(omit) }}"
    project_path: "{{ django_root }}"
    settings: "{{ settings }}"
    command: "migrate"
