#
# Create directories
#
# Input : django_root
# Output: dir_var, dir_run, dir_etc, dir_log, dir_static, dir_media,
#         dir_sendfile, dir_www, dir_venv
#

- name: "Directories"
  set_fact:
    dir_etc     : "{{ django_root }}/etc"
    dir_var     : "{{ django_root }}/var"
    dir_run     : "{{ django_root }}/var/run"
    dir_log     : "{{ django_root }}/var/log"
    dir_static  : "{{ django_root }}/var/static"
    dir_media   : "{{ django_root }}/var/media"
    dir_sendfile: "{{ django_root }}/var/sendfile"
    dir_www     : "{{ django_root }}/var/www"

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
  - "{{ dir_var }}"
  - "{{ dir_run }}"
  - "{{ dir_etc }}"
  - "{{ dir_log }}"
  - "{{ dir_static }}"
  - "{{ dir_media }}"
  - "{{ dir_sendfile }}"
  - "{{ dir_www }}"
