#
# Setup settings
#
# Input : django_root
# Output: settings, settings_file
# Requires:
#

#
# Secret key. All this code.. because lookups work in the local host instead of
# the target server. There should be a simpler way.
#
- name: "Secret key: facts"
  set_fact:
    secret_key_file: "{{ dir_var}}/secret.txt"
    secret_key_tmp: "/tmp/{{ local_user }}/ansible/{{ ansible_hostname }}/secret.txt"

- name: "Secret: fetch"
  fetch:
    src: "{{ secret_key_file }}"
    dest: "{{ secret_key_tmp }}"
    fail_on_missing: "no"
    flat: "yes"

- name: "Secret key: calculate"
  set_fact:
    secret_key: "{{ lookup('password',  secret_key_tmp + ' length=50') }}"

- name: "Secret key: copy"
  copy:
    src: "{{ secret_key_tmp }}"
    dest: "{{ secret_key_file }}"


#
# Settings proper
#
- name: "Settings: facts"
  set_fact:
    settings: "{{ django_project }}.settings"
    settings_file: "{{ django_root }}/{{ django_project }}/settings_ansible.py"

- filter_mods:
    base: "{{ django_root }}"
    dirs: "{{ mods }}"
    name: "settings.py"
    dest: "mods_settings"

- name: "Copy settings file"
  template:
    src: "settings_ansible.py.jinja"
    dest: "{{ settings_file }}"

#
# manage.py
#
- name: "Generate manage.py"
  template:
    src: "manage.py.jinja"
    dest: "{{ django_root }}/manage.py"
    mode: "u+x"

#
# urls
#

- filter_mods:
    base: "{{ django_root }}"
    dirs: "{{ mods }}"
    name: "urls.py"
    dest: "mods_urls"

- name: "Generate urls_ansible.py"
  template:
    src: "urls_ansible.py.jinja"
    dest: "{{ django_root }}/{{ django_project }}/urls_ansible.py"

#
# Migrations
# FIXME It says 'ok' when it should say 'changed'
#
- name: "Apply database migrations"
  django_manage:
    virtualenv: "{{ dir_venv|default(omit) }}"
    project_path: "{{ django_root }}"
    settings: "{{ settings }}"
    command: "migrate"
