#
# Setup virtual environment
#
# Input : virtualenv, prefix, django_root
# Output: dir_venv, dir_bin
# Requires:
#

- name: "Path to bin/ with virtual environment"
  set_fact:
    dir_venv    : "{{ django_root }}/venv{{ python_version_short }}"
    dir_bin     : "{{ django_root }}/venv{{ python_version_short }}/bin"
  when: virtualenv|bool

- name: "Path to bin/ with prefix"
  set_fact:
    dir_bin     : "{{ prefix }}/bin"
  when: "not virtualenv and prefix"

- name: "No path to bin/"
  set_fact:
    dir_bin     : null
  when: "not virtualenv and not prefix"

# Paths to binaries
- include: "bin.yml"

# Create virtual environment
- name: "Path to system's Python"
  which:
    name: "python{{ python_version }}"
    dest: "python_sys"
  when: virtualenv|bool

- name: "Create virtual environment"
  pip:
    chdir: "{{ django_root }}"
    name: "pip=={{ pip_version }}"
    virtualenv: "{{ dir_venv }}"
    virtualenv_command: "{{ python_sys + ' -m venv' }}"
  when: virtualenv|bool

- name: "Update path to pip"
  set_fact:
    pip: "{{ dir_venv }}/bin/pip"
  when: virtualenv|bool

# Update pip when not using a virtual environment
- name: "Update pip"
  pip:
    chdir: "{{ django_root }}"
    name: "pip=={{ pip_version }}"
    executable: "{{ pip }}"
  when: not virtualenv

# Install requirements
- name: "requirements.txt file from template"
  template:
    src: "requirements.txt"
    dest: "{{ dir_etc }}/requirements.txt"

- name: "Install requirements"
  pip:
    chdir: "{{ django_root }}"
    requirements: "{{ dir_etc }}/requirements.txt"
    executable: "{{ pip }}"
