#
# TODO Write a helper like which
#

- name: "Extra PYTHONPATH (1/2)"
  realpath:
    base: "{{ django_root }}"
    path: "{{ pythonpath }}"
  register: pythonpath
  when: pythonpath is not none

- name: "Extra PYTHONPATH (2/2)"
  set_fact:
    pythonpath: "{{ pythonpath.realpath }}"
  when: pythonpath is not none

#- debug: var=pythonpath
