#
# Expand root directory
#
# Input   : django_root (optional)
# Output  : django_root
# Requires:
#

# Case 1: root given, get the canonical form
- name: "Expand root"
  set_fact:
    django_root: "{{ django_root|realpath }}"
  when: "django_root != ''"

# Case 2: root not given, assume
- name: "Path to working tree root directory (1/2)"
  command: "git rev-parse --show-toplevel"
  register: "__aux"
  changed_when: false
  when: "django_root == ''"

- name: "Path to working tree root directory (2/2)"
  set_fact:
    django_root: "{{ __aux.stdout }}"
  when: "django_root == ''"
