#
# Uwsgi configuration
#
# Input : dir_etc, dir_run
# Output: file_sock, file_fifo, file_pid
# Requires:
#

- name: "Paths to ASGI files"
  set_fact:
    file_sock: "{{ dir_run }}/asgi.socket"
    file_pid : "{{ dir_run }}/asgi.pid"

- name: "Check ASGI server is running (1/2)"
  stat:
    path: "{{ file_pid }}"
  register: "__aux"

- name: "Check ASGI server is running (2/2)"
  set_fact:
    uvicorn_running: "{{ __aux.stat.exists }}"

- name: "ASGI configuration"
  template:
    src: "gunicorn.conf.py"
    dest: "{{ dir_etc }}/gunicorn.conf.py"
  notify: "reload uvicorn"

- name: "Start/Stop scripts"
  template:
    src: "{{ item }}"
    dest: "{{ dir_etc }}/{{ item }}"
    mode: "0744"
  with_items:
  - "start.sh"
  - "stop.sh"
